### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by hugsy** [De4dCr0w/green-dill#1]
Hi,

Great work on the plugin. I'd like to integrate some of your work into [`GEF`](https://github.com/hugsy/gef) which already provide some features for kernel debugging. However, there's no license to your repository.  Do you care to add one?

Thanks,

**Comment by De4dCr0w** [comment]
I have added the license to my repository. I‘m pleasure to see there are some contributions to GEF in my work.

Thanks

**Comment by hugsy** [comment]
That's great! Thanks!
